### ISSUE TITLE
Правки веб-морды

### ISSUE THREAD

**Issue by SerafimArts** [LaravelRUS/GitterBot#11]
- Оставить поисковую строчку на странице с профилем
  - При поиске в ней переходить на страницу со списком найденных пользователей
- Добавить кнопки\ссылки "написать личное сообщение", "профиль на гитхаб" и "профиль на laravel.su" в профиль пользователя
- Добавить отдельную страницу со списком всех доступных ачивок и их описаний

**Comment by Big-Shark** [comment]
Изменить фон под аватаркой и ачивками
Сделай на главной топ, или типа того
Изменить картинки ачивок на разные)
Исправить баг с Инвалид дата

**Comment by SerafimArts** [comment]
@Big-Shark 
1) фон взят с laravel.su: http://laravel.su/greabock http://karma.laravel.su/greabock
2) да, надо
3) Они разные, только не все =) 
![](https://raw.githubusercontent.com/LaravelRUS/GitterBot/master/resources/achieve/karma-500.gif) ![](https://raw.githubusercontent.com/LaravelRUS/GitterBot/master/resources/achieve/karma-10.gif)
4) Что за баг? о_0

**Comment by Big-Shark** [comment]
1) может тогда сделать 1 в 1 как на ларавель су, только снизу еще добавить ачивки, хотя и там тоже ачивки нужны
3) в маленьком размере как сейчас, не очень видно что там.
4) в списке поблагодаривших все вот такие 
AndrewNovikof
Сказал спасибо:
Invalid Date

Вообщем непонятно сколько раз сказал спасибо, и почему дата инвалид)

**Comment by SerafimArts** [comment]
1) Получение списка пользователей - http://karma.laravel.su/api/users.json Получение информации о конкретном пользователе по его gitter_id: http://karma.laravel.su/api/user/52f23d965e986b0712ef5e85.json Так что ачивки можно получить запросто. Это всё с вас.
3) По этому отдельную страницу и хочу запилить.
4) Мейджик, это что за браузер такой?

**Comment by Big-Shark** [comment]
1) оки доки @greabock @Butochnikov слышали?
3) ок
4) Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by SerafimArts** [comment]
1) @Butochnikov слышал и видел, @greabock нет. Естественно готов если что подправить, упростить, улучшить и т.д.
4) Ясно, ок, там значит JS объект Date глючный и в нём не работает `new Date('2015-10-14 07:34:17.000000')` если честно, не тестил =)

**Comment by SerafimArts** [comment]
Разнёс на несколько разных issue, что бы проще было отследить работу: https://github.com/LaravelRUS/GitterBot/issues/12 https://github.com/LaravelRUS/GitterBot/issues/13 https://github.com/LaravelRUS/GitterBot/issues/14 https://github.com/LaravelRUS/GitterBot/issues/15 https://github.com/LaravelRUS/GitterBot/issues/16 https://github.com/LaravelRUS/GitterBot/issues/17 https://github.com/LaravelRUS/GitterBot/issues/18
