### ISSUE TITLE
скажи спасибо сам себе

### ISSUE THREAD

**Issue by oknimdy** [LaravelRUS/GitterBot#23]
не добавит + в карму, но для "будьте здоровы" идет учет что ты "высказал спасибо" т.е. отдал свое спасибо самому себе

**Comment by oknimdy** [comment]
даже еще хуже, идет учет всего, просто пишет, что не учел

@oknimdy

```
карма
```

@KarmaBot

```
@oknimdy, Ваша карма +15. Вы благодарили 12 раз.
- Достижения: "Находчивый"
- Профиль oknimdy на laravel.su
```

@oknimdy

```
@oknimdy спасибо
```

@KarmaBot

```
Так не честно @oknimdy. Нельзя добавлять карму самому себе.
```

@oknimdy

```
карма
```

@KarmaBot

```
@oknimdy, Ваша карма +16. Вы благодарили 13 раз.
- Достижения: "Находчивый"
- Профиль oknimdy на laravel.su
```

**Comment by SerafimArts** [comment]
@oknimdy ничосси о_0

**Comment by SerafimArts** [comment]
https://github.com/LaravelRUS/GitterBot/commit/86c597add2d472488d5a2b9de12e13ad9dd1553f
