### ISSUE TITLE
@kto-to @ooPASHAoo спасибо

### ISSUE THREAD

**Issue by ooPASHAoo** [LaravelRUS/GitterBot#25]
сообщение:

> @kto-to @ooPASHAoo спасибо

ответ:

> Так не честно @ooPASHAoo. Нельзя добавлять карму самому себе.
> Так не честно @kto-to. Нельзя добавлять карму самому себе.

**Comment by SerafimArts** [comment]
Изменена архитектура анализа сообщений, вроде всё теперь работает:
https://github.com/LaravelRUS/GitterBot/blob/79edcd1574cc639a4c080eb2b0d1a23b83415276/app/Gitter/Karma/Validator.php
https://github.com/LaravelRUS/GitterBot/blob/79edcd1574cc639a4c080eb2b0d1a23b83415276/app/Middlewares/KarmaCounterMiddleware.php

**Comment by SerafimArts** [comment]
https://github.com/LaravelRUS/GitterBot/commit/79edcd1574cc639a4c080eb2b0d1a23b83415276
