### ISSUE TITLE
Убрать в "давай погуглю за тебя" g.zeos.in

### ISSUE THREAD

**Issue by symbios-zi** [LaravelRUS/GitterBot#26]
Очень напрягает этот медлительный сервис http://g.zeos.in/. Предлагаю сразу по ссылке выдавать результаты гугла.

**Comment by SerafimArts** [comment]
При попытке убрать этот сервис в прошлый раз, кто-то высказывался что нет, не стоит. 

Так что предлагаю вынести на обсуждение. В пятницу, 23.10.2015 в 22 по мск подвести итог.

Я голосую `"за"`, убрать нафиг этот сервис.

**Comment by Big-Shark** [comment]
за

**Comment by Malezha** [comment]
Убрать.

**Comment by symbios-zi** [comment]
За

**Comment by SerafimArts** [comment]
applied, merged

**Comment by symbios-zi** [comment]
при гуглении выдает страницу без результатов почему то.
