### ISSUE TITLE
Column not found: 1054 Unknown column 'status' in 'where clause'  

### ISSUE THREAD

**Issue by Big-Shark** [LaravelRUS/GitterBot#28]
➜  gitter git:(master) php artisan gitter:karma

  [Illuminate\Database\QueryExceptio  
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause' (SQL: select \* from `karma` where `status` = inc group by `user_target_id`)  

  [PDOException]  
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause'

**Comment by SerafimArts** [comment]
Сейчас на работе, поправить не могу, просьба убрать `where status = inc` в этой консольной команде или дождаться вечера =)

**Comment by SerafimArts** [comment]
Просто убрал команду, дабы не смущать и не поддерживать лишнее: https://github.com/LaravelRUS/GitterBot/commit/0fd9df9b3ba046850f3c6552c0a17d525b6ba262
