### ISSUE TITLE
При вставки большой картинки видео, или текста, бот должен писать что так делать не стоит

### ISSUE THREAD

**Issue by Big-Shark** [LaravelRUS/GitterBot#29]
Если человек вставляет картинку, видео с ютюба, или код больше 15 строк, то пишем что так лучше не делать, и залить все на паст бин, или обернуть в кавычки

**Comment by SerafimArts** [comment]
На gist. У нашего бота есть доступ к гитхабу, т.к. у него есть акк на гитхабе, что логично. А у него есть апишка, у гитхаба, подозреваю что можно запилить сквозь неё заливку на гист.

**Comment by Big-Shark** [comment]
@SerafimArts я думаю люди тогда будут пользоваться этим, для заливки любого кода на гист, хотя можно попробовать, может будет и удобно

**Comment by SerafimArts** [comment]
Добавлена миддлваря, сообщающая о том, что не стоит вставлять ссылки на видео и картинки: https://github.com/LaravelRUS/GitterBot/commit/21eb39877c191bb74734422f8f4df002e503419f https://github.com/LaravelRUS/GitterBot/commit/a1176c69180dd17dc67cfa3b3912448fd126c1df

**Comment by ghost** [comment]
Наверное, можно закрыть, т.к.: 
#41 - сообщения о длинном коде добавлены
#45 - сообщения о картинках/видео не только добавлены, но и, вероятно, будут удалены)

**Comment by SerafimArts** [comment]
@atehnix скорее надо вынести в отдельный issue. Добавить АПИ на гит, что бы он код автоматом публиковал туда, т.к. пока что он только предупреждает. М?

**Comment by ghost** [comment]
@SerafimArts можно. Только нужно тогда решать что делать с сообщениями, в которых несколько кусков кода c текстом между ними. 
Как вариант, отправлять одним куском, а перед строками текста добавлять `//`.

**Comment by SerafimArts** [comment]
@atehnix всё просто - несколько файлов аттачить. Гист это позволяет

**Comment by SerafimArts** [comment]
Вынесено в роадмап (https://github.com/LaravelRUS/GitterBot/issues/53) в улучшения `LongMessageMiddleware` миддлвари
