### ISSUE TITLE
Баг с приветствием

### ISSUE THREAD

**Issue by Big-Shark** [LaravelRUS/GitterBot#33]
@Big-Shark
@unnamed75 приветствую

KarmaBot 12:29
@Big-Shark, здравствуй.

Почему мне ответил бот?

**Comment by SerafimArts** [comment]
Потому что он отвечает только когда не указан ни один логин. Т.е. предполагает сообщение вида "привет всем"

**Comment by SerafimArts** [comment]
Ну вот такая кривая логика =(
https://github.com/LaravelRUS/GitterBot/blob/master/app/Middlewares/PersonalAnswersMiddleware.php#L41-L73

**Comment by Big-Shark** [comment]
Думаю надо добавить проверку на присутствия или отсутствия ника.

**Comment by SerafimArts** [comment]
Поправлено. В проде
