### ISSUE TITLE
Система ачивок

### ISSUE THREAD

**Issue by Rhincodon** [LaravelRUS/GitterBot#4]
Обсуждение возможных ачивок, нужны ли они вообще впринципе.

**Comment by Big-Shark** [comment]
Я за ачивки, если они будут показываться на сайте, и в чате во время получения, получить ачивку должно быть не очень легко) Они не долджны надоедать в чате

**Comment by SerafimArts** [comment]
@Big-Shark +1

**Comment by Butochnikov** [comment]
@Big-Shark поддержу такую формулировку

**Comment by SerafimArts** [comment]
Предлагаю перейти к предложениям непосредственно по ачивкам (за что их давать), существующие уже учитывают лишь количество кармы: 10, 50, 100 и 500 соответственно (https://github.com/LaravelRUS/GitterBot/tree/master/app/Subscribers/Achievements).

Предлагаю добавить:
- "Меценат". За 20 благодарностей другим людям.
- "Скорострел". За 10 сообщений в течении 10 секунд. (Хотя это может по-моему негативно отразиться на качестве информации в чате).
- "Писец". За 200 слов в одном сообщении.

**Comment by Big-Shark** [comment]
Мне кажется нужно пока только за спасибо, и ачивки которые выдаются вручную, допустим за пожертвование, или за особые заслуги, за статьи допустим.

**Comment by SerafimArts** [comment]
@Big-Shark Ну это довольно скучно и очевидно, ты не находишь? Ачивки - отличный мотиватор для людей. За статьи - согласен, они получаются довольно быстро, как и "карма 10", плюс помогают сообществу по очевидным причинам. 

Возможно можно запилить ачивки, вроде "10 ссылок на документацию" (поощряет чтение доков), "за использование всех доступных тегов маркдауна" (поощряет форматирование). М?

**Comment by Big-Shark** [comment]
@SerafimArts незнаю как ты будешь следить за форматированием, но можно и такой добавить, за ссылки тоже норм, я просто думаю что ачивки будут не только в чате, но и на сайте, поэтому както хотелось бы связать еще и с ними, допустим предложил 10 новостей в группу в ВК, или написал статью для ларавель.су, и тд

**Comment by SerafimArts** [comment]
Закрываю за неактуальностью. Если есть идеи - ставьте иссью "добавить блабла ачивку", добавим+
