### ISSUE TITLE
Убрать оповещения "оборачивать в код картинки"

### ISSUE THREAD

**Issue by SerafimArts** [LaravelRUS/GitterBot#45]
Думаю это не особо нужный функционал. Ставим `+` или `-` кто за (что бы убрать) и против (оставить) соответственно. Итоги подведём в воскресенье. =)

**Comment by SerafimArts** [comment]
+

**Comment by fortis** [comment]
++ убрать

**Comment by MelnixDev** [comment]
+

**Comment by fortis** [comment]
можно вынести в конфиг, если для огромных чатов это проблема и по дефолту не включать

**Comment by SerafimArts** [comment]
@fortis именно такой вариант и присутствует в дев ветке (например: https://github.com/LaravelRUS/GitterBot/blob/develop/config/gitter.php#L28) но проблему надо решить сейчас, т.к. дев ветка хз когда выкатится на продакшн, а сейчас пользоваться чатом кармабот может мешать, особенно для новичков. Как-то так, убирать не впиливать.

**Comment by Big-Shark** [comment]
##

**Comment by Dualse** [comment]
##

**Comment by ghost** [comment]
##

**Comment by SerafimArts** [comment]
Голосами 3х против 3х **временно** убираем, до тех пор, пока правила можно будет конфижить для определённых чатиков отдельно.
