### ISSUE TITLE
Починить бота

### ISSUE THREAD

**Issue by SerafimArts** [LaravelRUS/GitterBot#51]
Я не знаю что, но что-то надо починить точно.

Задача очень сложная, так что ответственным за её исполнение назначается @ruelephant, никто больше не справится.

@ruelephant, просьба ссылаться на этот таск в своих PR.

**Comment by ghost** [comment]
@SerafimArts можно закрывать. Починено в #84. ;)

**Comment by SerafimArts** [comment]
@atehnix ты молодец!
