### ISSUE TITLE
Баги когда бот работает слишком активно

### ISSUE THREAD

**Issue by Big-Shark** [LaravelRUS/GitterBot#6]
@Big-Shark последнее использовал)
спасибо @Big-Shark
  )
KarmaBot 14:36
Спасибо принято. Текущая карма пользователя @Big-Shark +35
Спасибо принято. Текущая карма пользователя @Big-Shark +36
Big-Shark 14:37
Омг

NelinD 14:50
@Big-Shark тест спасибо @Big-Shark и еще разок @Big-Shark
@Big-Shark тест @Big-Shark тест спасибо @Big-Shark
KarmaBot 14:50
Спасибо принято. Текущая карма пользователя @Big-Shark +38
Спасибо принято. Текущая карма пользователя @Big-Shark +37
Спасибо принято. Текущая карма пользователя @Big-Shark +39

**Comment by oknimdy** [comment]
спасибо
