### ISSUE TITLE
Изменить немного алгоритм гуглинга

### ISSUE THREAD

**Issue by Big-Shark** [LaravelRUS/GitterBot#9]
Если идет обращение от ника к боту вот такое

```
@greabock 
@KarmaBot погугли карма
KarmaBot 14:35
@KarmaBot погуглил для тебя
```

То мне кажется бот должен отвечать этому же человеку, а не себе.

**Comment by Big-Shark** [comment]
добавить "гугли ..."

**Comment by SerafimArts** [comment]
- Теперь при запросе "@KarmaBot погугли" отвечает "погуглил" (ссылкой)
- Теперь при запросе "гугли что-то", отвечает "погуглил" (ссылкой)
- На все остальные запросы, например "@Big-Shark погугли что-то", отвечает "@Big-Shark погуглил для тебя".

Протестировано, в продакшене. @Big-Shark просьба проверить и закрыть иссью, если всё устраивает.

**Comment by Big-Shark** [comment]
@SerafimArts пускай при `@KarmaBot погугли ...` отвечает человеку, и с текстом `погуглил для тебя`
а если просто без адресата, то и отвечает без адресата.

**Comment by SerafimArts** [comment]
Fixed:
1) https://github.com/LaravelRUS/GitterBot/commit/1e9850e650227c9c2cbfa315fe63fbfd0d231d8d
2) https://github.com/LaravelRUS/GitterBot/commit/b40b20736947c276dc8f2be34c73699efdccd4a2
