### ISSUE TITLE
Устаревшая ссылка на доки по Laravel

### ISSUE THREAD

**Issue by butschster** [LaravelRUS/GitterBot#90]
При поиске по документации Laravel, в индексе версия 5.3, а в ссылке подставляется версия 5.2 и ссылка оказывается битой

Сссылка формируется здесь:
https://github.com/LaravelRUS/KarmaBot/blob/master/app/Domains/Bot/Middlewares/LaravelDocumentationSearcherMiddleware.php#L46

**Comment by SerafimArts** [comment]
https://github.com/LaravelRUS/KarmaBot/pull/89
